language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

install:
  - make setup
  - pip install coveralls

cache:
  directories:
  - $HOME/.cache/pip

script:
  - make test

after_success:
  - coveralls
